### PR TITLE
Update packages: grunt, grunt-contrib-jshint, moca

### PR DESCRIPTION
**Pull request by johnhenry**
# Update **grunt** to remove external dependency
This currently fails to install as a third-party package because running the **postinstall** script produces the following error when `grunt` is not installed globally:
```
sh: grunt: command not found
```
I've updated to the latest version of grunt to fix this. 
## Specific Changes:
grunt: 0.4.5 -> ^1.0.3

# Update **grunt-contrib-jshint** and **moca** to address security vunerabilities
I've also updated to the latest versions of `grunt-contrib-jshint` and `moca` to address security vulnerabilities.

```
found 14 vulnerabilities (7 low, 6 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

## Specific Changes:
grunt-contrib-jshint: ~0.2.0 -> 2.0.0
mocha: 2.4.5 -> 5.2.0

### CODE REVIEW

**Comment by johnhenry** [comment]
@jnogol I would to update the changelog, but I could not find it in the repository or wiki. Could you point me to it?

**Comment by jnogol** [comment]
Good point. Could you pull from `develop`? Looks like it wasn't merged to master back then

**Comment by johnhenry** [comment]
@dortegau, as mentioned in the description currently when I try to install this on a locally to use in other projects, I get this error:

```bash
sh: grunt: command not found
```

Updating grunt from 0.4.5 to ^1.0.3 removes this error. 
BUT, installing grunt globally also removes this error, so I identified it as a [hidden] dependency. Would it be better to mark this as an error?

**Comment by dortegau** [comment]
Merged! 

Thanks for your contribution 👍

**Comment by dortegau** [comment]
tlsh version 1.0.6 with your changes has been published: https://www.npmjs.com/package/tlsh

Thanks for contributing!

**Pull request merged**
